  [build]
    command = "npm run build"
    publish = "build"

  [build.environment]
    NODE_OPTIONS = "--max-old-space-size=4096"

  [functions]
    directory = "functions"
    node_bundler = "esbuild"

  [[redirects]]
    from = "/calendar.ics"
    to = "/.netlify/functions/calendar-feed"
    status = 200

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200