name: 🐞 Bug Report
title: '[bug] '
description: Report a bug
labels: ['🐛 bug', '🧹 needs triage']

body:
  - type: markdown
    attributes:
      value: |
        ## Checklist
        1. First reach out over our discord as it's usually the best place to get the fastest support as there are mostly likely others experiencing the same issues as you and active Teia team members assisting with troubleshooting. Please seek help in the #help channel, and read recent dev updates in #announcements. You can join the discord here: https://discord.gg/AmG86s7nfe
        2. Please search for [existing issues](https://github.com/teia-community/teia-ui/issues?q=is%3Aissue) about this problem first.

        *See transaction history for an objkt*
        https://hicdex.com/objkt

        *See transaction history for your wallet address*
        https://hicdex.com/sold

  - type: markdown
    attributes:
      value: |
        **If you need help with minting or managing assets, please give us the following information**
          - your profile link
          - any other profile links affected
          - tezos wallet address
          - objkt #'s that are being affected
          - screenshots of the browser console (in chrome windows, press ctrl + shift + j to open the developer console)

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.
  - type: markdown
    attributes:
      value: |
        **Platform (please complete the following information):**

  - type: textarea
    id: info
    attributes:
      label: Platform and versions
      description: 'Output of `npm run tauri info` or `cargo tauri info`'
      render: shell
      placeholder: |
        - OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Stack trace
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
