name: 📷 Playwright Screenshots
on:
  workflow_dispatch:

jobs:
  take-screenshots:
    concurrency: ci-${{ github.ref }}
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --maxsockets 1
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot/
          retention-days: 30
